#!/usr/bin/env bash
## system_defaults :: System :: Defaults

#
## Initialization :: Phase 0

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit
set -u

#
## Initialization :: Variables :: Static

# Variable modification :: Script :: Short name
readonly cr_script_sn='run_220_system_defaults'

# Variable modification :: Checksum :: Defaults
readonly cr_checksum_defaults="$HOME/.config/chezmoi/checksum/$cr_script_sn/defaults"

# Variable modification :: Source :: Defaults
readonly cr_source_defaults="$HOME/.local/share/chezmoi/.data/$cr_script_sn/defaults"

#
## Preprocess :: Phase 0

# Validate :: Determine checksum file :: Defaults
if [ -e "$cr_checksum_defaults" ]; then
    # Validate :: Determine checksum :: Data entity
    if [ "$(LC_ALL=C shasum --algorithm 512256 --text "$cr_source_defaults" | sed 's/^\([a-z0-9]\{64\}\)  .*$/\1/')" = "$(cat "$cr_checksum_defaults")" ]; then
        # Action :: Graceful exit
        exit 0
    fi
fi

#
## Main :: Phase 0

# Action :: Apply :: Defaults
# shellcheck source=/dev/null
. "$cr_source_defaults"

#
## Postprocess :: Phase 0

# Validate :: Existence directory :: $HOME/.config/chezmoi/checksum/$cr_script_sn
if [ ! -d "$HOME/.config/chezmoi/checksum/$cr_script_sn" ]; then
    # Directory modification :: $HOME/.config/chezmoi/checksum/$cr_script_sn
    mkdir -v "$HOME/.config/chezmoi/checksum/$cr_script_sn"
fi

#
## Postprocess :: Phase 1

# Validate :: Determine checksum file :: Defaults
if [ -e "$cr_checksum_defaults" ]; then
    # Action :: defaults :: Dock :: Wipe all app icons from the Dock
    defaults write com.apple.dock persistent-apps -array
fi

#
## Postprocess :: Phase 2

# File modification :: $cr_checksum_defaults
LC_ALL=C shasum --algorithm 512256 --text "$cr_source_defaults" | sed 's/^\([a-z0-9]\{64\}\)  .*$/\1/' >"$cr_checksum_defaults" || {
    # Notify :: Checksum failure
    printf '%s\n' "FAIL :: shasum :: $cr_source_defaults :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}
