#!/usr/bin/env bash
## assh_config_build :: assh :: Config :: Build

#
## Initialization :: Phase 0

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit
set -u

#
## Initialization :: Variables :: Static

# Variable modification :: Script :: Short name
readonly cr_script_sn='run_230_assh_config_build'

#
## Initialization :: Variables :: Dynamic

# Variable modification :: State :: Success
readonly cr_state_success="$HOME/.config/chezmoi/state/$cr_script_sn"

#
## Preprocess :: Phase 0

# Validate :: Determine state :: Success
if [ -e "$cr_state_success" ]; then
    # Action :: Graceful exit
    exit 0
fi

#
## Preprocess :: Phase 1

# Validate :: Determine existence of assh binary
if [[ ! -e '/usr/local/bin/assh' ]]; then
    # Notify :: Missing binary
    printf '%s\n' "FAIL :: Missing binary :: /usr/local/bin/assh :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
fi

# Validate :: Determine existence of assh configuration
if [[ ! -e "$HOME/.ssh/assh.yml" ]]; then
    # Notify :: Missing configuration
    printf '%s\n' "FAIL :: Missing configuration :: $HOME/.ssh/assh.yml :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
fi

#
## Main :: Phase 0

# Action :: assh :: Build configuration
assh config build >"$HOME/.ssh/config" || {
    # Notify :: Execution failure
    printf '%s\n' "FAIL :: assh :: Config :: Build :: $HOME/.ssh/config :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}

#
## Postprocess :: Phase 0

# File modification :: $cr_state_success
touch "$cr_state_success" || {
    # Notify :: touch failure
    printf '%s\n' "FAIL :: touch :: $cr_state_success :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}
