#!/usr/bin/env bash
## forklift_favorites :: ForkLift :: Favorites

#
## Initialization :: Phase 0

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit
set -u

#
## Initialization :: Variables :: Static

# Variable modification :: Script :: Short name
readonly cr_script_sn='run_510_forklift_favorites'

#
## Initialization :: Variables :: Dynamic

# Variable modification :: Checksum :: ForkLift :: Favorites
readonly cr_checksum_forklift_favorites="$HOME/.config/chezmoi/checksum/$cr_script_sn/Favorites.json"

# Variable modification :: Target :: ForkLift :: Favorites
readonly cr_target_forklift_favorites="$HOME/.local/share/chezmoi/.data/$cr_script_sn/Favorites.json"

#
## Preprocess :: Phase 0

# Validate :: Existence checksum file :: ForkLift :: Favorites
if [[ -e "$cr_checksum_forklift_favorites" ]]; then
    # Validate :: Determine checksum :: Data entity
    if [[ "$(LC_ALL=C shasum --algorithm 512256 --text "$cr_target_forklift_favorites" | sed 's/^\([a-z0-9]\{64\}\)  .*$/\1/')" = "$(cat "$cr_checksum_forklift_favorites")" ]]; then
        # Action :: Graceful exit
        exit 0
    fi
fi

#
## Main :: Phase 0

# Validate :: Determine existence of Favorites directory
if [[ ! -d "$HOME/Library/Application Support/ForkLift/Favorites" ]]; then
    # Directory modification :: $HOME/Library/Application Support/ForkLift/Favorites
    mkdir -p "$HOME/Library/Application Support/ForkLift/Favorites"
fi

# File modification :: $HOME/Library/Application Support/ForkLift/Favorites/Favorites.json
cp -v "$cr_target_forklift_favorites" "$HOME/Library/Application Support/ForkLift/Favorites/Favorites.json" || {
    # Notify :: Copy failure
    printf '%s\n' "FAIL :: cp :: $cr_target_forklift_favorites :: $HOME/Library/Application Support/ForkLift/Favorites/Favorites.json :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}

#
## Postprocess :: Phase 0

# Validate :: Existence directory :: $HOME/.config/chezmoi/checksum/$cr_script_sn
if [[ ! -d "$HOME/.config/chezmoi/checksum/$cr_script_sn" ]]; then
    # Directory modification :: $HOME/.config/chezmoi/checksum/$cr_script_sn
    mkdir -v "$HOME/.config/chezmoi/checksum/$cr_script_sn"
fi

# File modification :: $cr_checksum_forklift_favorites
LC_ALL=C shasum --algorithm 512256 --text "$cr_target_forklift_favorites" | sed 's/^\([a-z0-9]\{64\}\)  .*$/\1/' >"$cr_checksum_forklift_favorites" || {
    # Notify :: Checksum failure
    printf '%s\n' "FAIL :: shasum :: $cr_target_forklift_favorites :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}
