#!/usr/bin/env sh
## homebrew_packages_node :: Homebrew :: Packages :: Node

#
## Initialization :: Phase 0

# Fail-safe :: Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit
set -u

#
## Initialization :: Variables :: Static

# Variable modification :: Script :: Short name
readonly cr_script_sn='run_212_homebrew_packages_node'

#
## Initialization :: Variables :: Dynamic

# Variable modification :: Checksum :: Brewfile :: Node
readonly cr_checksum_brewfile_node="$HOME/.config/chezmoi/checksum/$cr_script_sn/brewfile.node"

# Variable modification :: Source :: Brewfile :: node
readonly cr_source_brewfile_node="$HOME/.Brewfile.node"

#
## Preprocess :: Phase 0

# Validate :: Existence checksum file :: Brewfile :: Node
if [ -e "$cr_checksum_brewfile_node" ]; then
    # Validate :: Determine checksum :: Data entity
    if [ "$(LC_ALL=C shasum --algorithm 512256 --text "$cr_source_brewfile_node" | sed 's/^\([a-z0-9]\{64\}\)  .*$/\1/')" = "$(cat "$cr_checksum_brewfile_node")" ]; then
        # Action :: Graceful exit
        exit 0
    fi
fi

#
## Main :: Phase 0

# Action :: Homebrew :: Install :: Packages :: Node
brew bundle install --file="$cr_source_brewfile_node" # || {
#     # Notify :: Execution failure
#     printf '%s\n' "FAIL :: brew :: bundle install :: node :: $cr_script_sn/$LINENO"
#     # Action :: Exit ungracefully
#     exit 1
# } // NOTE :: Disabled as brew bundle install occasionally exits ungracefully

# Action :: Homebrew :: Cleanup :: Prune :: Remove stale lock files and outdated downloads for all formulae and casks, and remove old versions of installed formulae
brew cleanup --prune 0 # || {
#     # Notify :: Execution failure
#     printf '%s\n' "FAIL :: brew :: cleanup :: --prune 0 :: $cr_script_sn/$LINENO"
#     # Action :: Exit ungracefully
#     exit 1
# # } // NOTE :: Disabled as brew cleanup occasionally exits ungracefully

#
## Postprocess :: Phase 0

# Validate :: Existence directory :: $HOME/.config/chezmoi/checksum/$cr_script_sn
if [ ! -d "$HOME/.config/chezmoi/checksum/$cr_script_sn" ]; then
    # Directory modification :: $HOME/.config/chezmoi/checksum/$cr_script_sn
    mkdir -v "$HOME/.config/chezmoi/checksum/$cr_script_sn"
fi

# File modification :: $cr_checksum_brewfile_node
LC_ALL=C shasum --algorithm 512256 --text "$cr_source_brewfile_node" | sed 's/^\([a-z0-9]\{64\}\)  .*$/\1/' >"$cr_checksum_brewfile_node" || {
    # Notify :: Checksum failure
    printf '%s\n' "FAIL :: shasum :: $cr_source_brewfile_node :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}
