#!/usr/bin/env bash
## chezmoi_cleanup :: chezmoi :: Cleanup

#
## Initialization :: Phase 0

# Fail-safe :: Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully
set -o pipefail

# Fail-safe :: Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit
set -u

#
## Initialization :: Variables :: Static

# Variable modification :: Script :: Short name
readonly cr_script_sn='run_950_chezmoi_cleanup'

#
## Initialization :: Variables :: Dynamic

# Variable modification :: State :: Success
readonly cr_state_success="$HOME/.config/chezmoi/state/$cr_script_sn"

#
## Preprocess :: Phase 0

# Validate :: Determine state :: Success
if [[ -e "$cr_state_success" ]]; then
    # Action :: Graceful exit
    exit 0
fi

#
## Main :: Phase 0

# Validate :: Determine existence of temporary chezmoi binary installation
if [[ -e "$HOME/bin/chezmoi" ]]; then
    # File modification :: $HOME/bin/chezmoi
    rm -f "$HOME/bin/chezmoi" || {
        # Notify :: Removal failure
        printf '%s\n' "FAIL :: rm :: $HOME/bin/chezmoi :: $cr_script_sn/$LINENO"

        # Action :: Exit ungracefully
        exit 1
    }
fi

# Validate :: Determine existence of temporary chezmoi binary directory
if [[ -d "$HOME/bin" ]]; then
    # Directory modification :: $HOME/bin
    rmdir "$HOME/bin" 2>/dev/null || { true; }
fi

#
## Postprocess :: Phase 0

# File modification :: $cr_state_success
touch "$cr_state_success" || {
    # Notify :: touch failure
    printf '%s\n' "FAIL :: touch :: $cr_state_success :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}
