#!/usr/bin/env sh
## homebrew_installation :: Homebrew :: Installation

#
## Initialization :: Phase 0

# Fail-safe :: Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion. An error message will be written to the standard error, and a non-interactive shell will exit
set -u

#
## Initialization :: Variables :: Static

# Variable modification :: Script :: Short name
readonly cr_script_sn='run_210_homebrew_installation'

#
## Initialization :: Variables :: Dynamic

# Variable modification :: State :: Success
readonly cr_state_success="$HOME/.config/chezmoi/state/$cr_script_sn"

#
## Preprocess :: Phase 0

# Validate :: Determine state :: Success
if [ -e "$cr_state_success" ]; then
    # Action :: Graceful exit
    exit 0
fi

#
## Main :: Phase 0

# Validate :: Determine usage of HTTPS based Git remote url
if [ ! -e '/usr/local/Homebrew/bin/brew' ]; then
    # Action :: Homebrew :: Install
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || {
        # Notify :: Execution failure
        printf '%s\n' "FAIL :: ruby-curl :: Homebrew :: $cr_script_sn/$LINENO"

        # Action :: Exit ungracefully
        exit 1
    }
fi

#
## Postprocess :: Phase 0

# File modification :: $cr_state_success
touch "$cr_state_success" || {
    # Notify :: touch failure
    printf '%s\n' "FAIL :: touch :: $cr_state_success :: $cr_script_sn/$LINENO"

    # Action :: Exit ungracefully
    exit 1
}
