#!/usr/bin/env bash

#
## Variables :: Static

# Mailbox
readonly sr_mailbox='smp-10510-g8f'

#
## Main :: Phase 0

# Action :: notmuch :: Batch process tagging directives
notmuch --config="$HOME/.notmuch/$sr_mailbox.config" tag --batch --input="$HOME/.notmuch/$sr_mailbox.tags"
